//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERMANAGEMENT_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COMPUTERMANAGEMENT_TestEntities : DbContext
    {
        public COMPUTERMANAGEMENT_TestEntities()
            : base("name=COMPUTERMANAGEMENT_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Asignacion> t_Asignacion { get; set; }
        public virtual DbSet<t_Equipo> t_Equipo { get; set; }
        public virtual DbSet<t_Factura> t_Factura { get; set; }
        public virtual DbSet<t_Marca> t_Marca { get; set; }
        public virtual DbSet<t_Modelo> t_Modelo { get; set; }
        public virtual DbSet<t_Producto> t_Producto { get; set; }
        public virtual DbSet<t_SistemaO> t_SistemaO { get; set; }
        public virtual DbSet<t_Tipo> t_Tipo { get; set; }
        public virtual DbSet<t_Usuario> t_Usuario { get; set; }
    }
}
