//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERMANAGEMENT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Asignacion
    {
        public int IdAsignacion { get; set; }
        public int Equipo { get; set; }
        public int Usuario { get; set; }
    
        public virtual t_Equipo t_Equipo { get; set; }
        public virtual t_Usuario t_Usuario { get; set; }
    }
}
