//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERMANAGEMENT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Factura()
        {
            this.t_Producto = new HashSet<t_Producto>();
        }
    
        public int IdFactura { get; set; }
        public string Factura { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Gatantia { get; set; }
        public string Proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Producto> t_Producto { get; set; }
    }
}
