//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERMANAGEMENT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Producto()
        {
            this.t_Equipo = new HashSet<t_Equipo>();
        }
    
        public int IdProducto { get; set; }
        public int Tipo { get; set; }
        public int Marca { get; set; }
        public int Modelo { get; set; }
        public Nullable<int> SistemaO { get; set; }
        public Nullable<int> Factura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Equipo> t_Equipo { get; set; }
        public virtual t_Factura t_Factura { get; set; }
        public virtual t_Marca t_Marca { get; set; }
        public virtual t_Modelo t_Modelo { get; set; }
        public virtual t_SistemaO t_SistemaO { get; set; }
        public virtual t_Tipo t_Tipo { get; set; }
    }
}
